### ISSUE TITLE
App crash when in landscape mode on profile pages

### ISSUE THREAD

**Issue by kennymc-c** [albaintor/UC-Remote#22]
When you switch to landscape mode with Build 114 on the profile pages the app crashes. I've sent the logs via TestFlight. The app also crashes when you switch back to portrait or directly start the app in landscape mode.

**Comment by albaintor** [comment]
Fixed in next release

**Comment by kennymc-c** [comment]
Confirmed, fixed with Build 115

**Comment by kennymc-c** [comment]
I need to reopen this issue as I had these crashed again with Build 120. But they are not happening every time

**Comment by albaintor** [comment]
Is still the same view involved ?
Have you tried to disable volume physical buttons as I also suspect a side effect with it (changing views including rotation make physical volume buttons unassigned then reassign with unsafe thread operations)

**Comment by albaintor** [comment]
I think I have fixed it in the next build

**Comment by kennymc-c** [comment]
Looks good with Build 121
