### ISSUE TITLE
Show entity command errors

### ISSUE THREAD

**Issue by kennymc-c** [albaintor/UC-Remote#48]
If an entity commands fails for some reason the app doesn't show this error. This should be supported as the user doesn't always know if a command has succeeded or not.

**Comment by albaintor** [comment]
Actually errors are shown while in a "sub-page" i.e activities, remote, media players views.
But indeed not in the profile pages.

**Comment by kennymc-c** [comment]
I don't see any errors on sub pages either

**Comment by albaintor** [comment]
I added some errors on profile pages as well but not on sliders : it can be annoying to receive repeated error messages when moving slider and in my case it occurs oftently. The remote has weak network performances (wifi chip/antenna) and even if connected it doesn't handle all requests successfully.

**Comment by albaintor** [comment]
Fixed in build 133. Please close the issue if all errors (except sliders) are raised

**Comment by kennymc-c** [comment]
I still don't see any command errors with 1.2.0 (133). To be clear: I'm refering to the response status codes that e.g. integrations send to tell the core if a command succeded or failed and are are also shown on the remote as internal server error etc.
Maybe you even could also show the error and info messages from the integration right before the error if you somehow can get acces to these log messages.

**Comment by albaintor** [comment]
Ok no I don't analyze the errors status. Just the same error message (still contextualized with the concerned entity)

**Comment by albaintor** [comment]
Switched to low priority. This would need a lot of refactoring

**Comment by kennymc-c** [comment]
FYI: Your own Remote Toolkit can display these error messages. I would be fine if the same messages appear in the app as well.

**Comment by kennymc-c** [comment]
1.5.1 should support this according to the changelog but I still don't see any error messages like Bad request. They also not appearing in the log.

**Comment by albaintor** [comment]
This is strange, it worked once and now there are no more toasts....

**Comment by albaintor** [comment]
Actually it works but not everywhere : UI items with icons don't raise any toast message unlike buttons. This will be fixed in 1.5.2

**Comment by kennymc-c** [comment]
Yes, its working with buttons but with all activity ui page items not toast message appears (text or icon)

**Comment by albaintor** [comment]
Yes I meant all ui items except a few ones (on/off activity...)

**Comment by kennymc-c** [comment]
Thanks, confirmed it's fixed with 1.5.2
